[workspace]
members = [
	"node",
	"runtime",
	"pallets/template",
	"pallets/template-2",
	"pallets/poe",
	"pallets/kitties",
	"pallets/ocw-tutorials",
	"pallets/ocw-homework",
]
[profile.release]
panic = "unwind"
